/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */
import type { HttpResponse as AngularHttpResponse, HttpContext, HttpEvent, HttpParams } from '@angular/common/http';
import { HttpClient, HttpHeaders } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type { GetApiLookupCitiesSearchParams } from '../../model';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?: HttpParams | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
}

function filterParams(
  params: Record<string, unknown>,
  requiredNullableKeys: Set<string> = new Set()
): Record<string, string | number | boolean | Array<string | number | boolean>> {
  const filteredParams: Record<string, string | number | boolean | null | Array<string | number | boolean>> = {};
  for (const [key, value] of Object.entries(params)) {
    if (Array.isArray(value)) {
      const filtered = value.filter(
        (item) => item != null && (typeof item === 'string' || typeof item === 'number' || typeof item === 'boolean')
      ) as Array<string | number | boolean>;
      if (filtered.length) {
        filteredParams[key] = filtered;
      }
    } else if (value === null && requiredNullableKeys.has(key)) {
      filteredParams[key] = null;
    } else if (
      value != null &&
      (typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean')
    ) {
      filteredParams[key] = value as string | number | boolean;
    }
  }
  return filteredParams as Record<string, string | number | boolean | Array<string | number | boolean>>;
}

@Injectable({ providedIn: 'root' })
export class LookupService {
  private readonly http = inject(HttpClient);
  getApiLookupContactEmail<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupContactEmail<TData = void>(
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupContactEmail<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupContactEmail<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/contact-email`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/contact-email`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/contact-email`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupCountries<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupCountries<TData = void>(
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCountries<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCountries<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/countries`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/countries`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/countries`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupProvinces<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupProvinces<TData = void>(
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupProvinces<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupProvinces<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/provinces`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/provinces`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/provinces`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupCities<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupCities<TData = void>(options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
  getApiLookupCities<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCities<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/cities`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCitiesSearch<TData = void>(
    params?: GetApiLookupCitiesSearchParams,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    const filteredParams = filterParams({ ...params, ...options?.params }, new Set<string>([]));

    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/cities/search`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events',
        params: filteredParams
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/cities/search`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response',
        params: filteredParams
      });
    }

    return this.http.get<TData>(`/api/Lookup/cities/search`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body',
      params: filteredParams
    });
  }
  getApiLookupCountryCountryCities<TData = void>(
    country: string,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCountryCountryCities<TData = void>(
    country: string,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCountryCountryCities<TData = void>(
    country: string,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCountryCountryCities<TData = void>(
    country: string,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/country/${country}/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/country/${country}/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/country/${country}/cities`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCountryCountryIdProvinceProvinceIdCities<TData = void>(
    countryId: string,
    provinceId: string,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/country/${countryId}/province/${provinceId}/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/country/${countryId}/province/${provinceId}/cities`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/country/${countryId}/province/${provinceId}/cities`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupCourts<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupCourts<TData = void>(options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
  getApiLookupCourts<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupCourts<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/courts`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/courts`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/courts`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupOffences<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupOffences<TData = void>(options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
  getApiLookupOffences<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupOffences<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/offences`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/offences`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/offences`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  getApiLookupRates<TData = void>(options?: HttpClientOptions & { observe?: 'body' }): Observable<TData>;
  getApiLookupRates<TData = void>(options?: HttpClientOptions & { observe: 'events' }): Observable<HttpEvent<TData>>;
  getApiLookupRates<TData = void>(
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  getApiLookupRates<TData = void>(
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.get<TData>(`/api/Lookup/rates`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.get<TData>(`/api/Lookup/rates`, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.get<TData>(`/api/Lookup/rates`, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
}
