#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum VSd_Rest_RestitutionDesiredOutcomes
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Assistance (navigating system, payment planning, reminders)", 1, "#0000ff")]
		AssistanceNavigatingSystemPaymentPlanningReminders = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Avoid civil court/ other consequences", 0, "#0000ff")]
		AvoidCivilCourtOtherConsequences = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Comply with order or PO instructions", 2, "#0000ff")]
		ComplyWithOrderOrPoInstructions = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Convenient payment method", 3, "#0000ff")]
		ConvenientPaymentMethod = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Intermediary (eliminate need for direct contact)", 4, "#0000ff")]
		IntermediaryEliminateNeedForDirectContact = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 8, "#0000ff")]
		Other = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pardon", 5, "#0000ff")]
		Pardon = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prefer not to answer", 6, "#0000ff")]
		PreferNotToAnswer = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Statements (record keeping)", 7, "#0000ff")]
		StatementsRecordKeeping = 100000007,
	}
}
#pragma warning restore CS1591
