#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum VSd_PaymentPlanPaymentMethod
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("BC Express Pay", 0, "#0000ff")]
		BcExpressPay = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cash", 1, "#0000ff")]
		Cash = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Cheque", 2, "#0000ff")]
		Cheque = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Correctional Service of Canada Institutional Account Transfer", 3, "#0000ff")]
		CorrectionalServiceOfCanadaInstitutionalAccountTransfer = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Internal Adjustment", 5, "#0000ff")]
		InternalAdjustment = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Money Order", 4, "#0000ff")]
		MoneyOrder = 100000005,
	}
}
#pragma warning restore CS1591
