#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum VSd_Temp_Province
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Alabama", 0, "#0000ff")]
		Alabama = 100000063,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Alaska", 1, "#0000ff")]
		Alaska = 100000064,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Alberta", 2)]
		Alberta = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Arizona", 3)]
		Arizona = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Arkansas", 4, "#0000ff")]
		Arkansas = 100000065,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Auckland", 5)]
		Auckland = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Australian Capital Territory", 6, "#0000ff")]
		AustralianCapitalTerritory = 100000088,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("British Columbia", 7)]
		BritishColumbia = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Buckinghamshire", 8)]
		Buckinghamshire = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("California", 9)]
		California = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Chungcheongnam", 10)]
		Chungcheongnam = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Colorado", 11)]
		Colorado = 100000007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Connecticut", 12)]
		Connecticut = 100000008,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Delaware", 13, "#0000ff")]
		Delaware = 100000066,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Demerara Mahaica", 14)]
		DemeraraMahaica = 100000009,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("District of Columbia", 15, "#0000ff")]
		DistrictOfColumbia = 100000067,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Dorset", 16)]
		Dorset = 100000010,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Edinburgh", 17)]
		Edinburgh = 100000011,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("England", 18)]
		England = 100000012,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Essex", 19)]
		Essex = 100000013,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Federal District", 20)]
		FederalDistrict = 100000014,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Federated States of Micronesia", 21, "#0000ff")]
		FederatedStatesOfMicronesia = 100000094,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Florida", 22)]
		Florida = 100000015,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Georgetown", 23)]
		Georgetown = 100000016,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Georgia", 24)]
		Georgia = 100000017,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Grand Cayman", 25)]
		GrandCayman = 100000018,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Havanna City", 26)]
		HavannaCity = 100000019,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hawaii", 27)]
		Hawaii = 100000020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hermer", 28)]
		Hermer = 100000021,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Hong Kong", 29)]
		HongKong = 100000022,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Idaho", 30)]
		Idaho = 100000023,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Illinois", 31)]
		Illinois = 100000024,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Indiana", 32, "#0000ff")]
		Indiana = 100000068,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Iowa", 33, "#0000ff")]
		Iowa = 100000069,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ireland Northern", 34)]
		IrelandNorthern = 100000025,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kansas", 35, "#0000ff")]
		Kansas = 100000070,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kentucky", 36, "#0000ff")]
		Kentucky = 100000071,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Kibuye", 37)]
		Kibuye = 100000026,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Louisiana", 38)]
		Louisiana = 100000027,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Maine", 39, "#0000ff")]
		Maine = 100000072,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Manitoba", 40)]
		Manitoba = 100000028,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Marshall Islands", 42, "#0000ff")]
		MarshallIslands = 100000095,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Maryland", 41)]
		Maryland = 100000029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Massachusetts", 43, "#0000ff")]
		Massachusetts = 100000073,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Michigan", 44)]
		Michigan = 100000030,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Minnesota", 45, "#0000ff")]
		Minnesota = 100000074,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mississippi", 46, "#0000ff")]
		Mississippi = 100000075,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Missouri", 47)]
		Missouri = 100000031,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Mombasa", 48)]
		Mombasa = 100000032,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Montana", 49, "#0000ff")]
		Montana = 100000076,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nebraska", 50, "#0000ff")]
		Nebraska = 100000077,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nevada", 51)]
		Nevada = 100000033,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("New Brunswick", 52)]
		NewBrunswick = 100000034,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Newfoundland", 57)]
		Newfoundland = 100000037,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("New Hampshire", 53, "#0000ff")]
		NewHampshire = 100000078,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("New Jersey", 54)]
		NewJersey = 100000035,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("New Mexico", 55, "#0000ff")]
		NewMexico = 100000079,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("New York", 56)]
		NewYork = 100000036,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nicosia", 58)]
		Nicosia = 100000038,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("North Carolina", 59, "#0000ff")]
		NorthCarolina = 100000080,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("North Dakota", 60)]
		NorthDakota = 100000039,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Northern Territory", 63, "#0000ff")]
		NorthernTerritory = 100000093,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Northwest Territories", 62)]
		NorthwestTerritories = 100000040,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nothern Mariana Islands", 61, "#0000ff")]
		NothernMarianaIslands = 100000096,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nova Scotia", 64)]
		NovaScotia = 100000041,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Nunavut", 65)]
		Nunavut = 100000042,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ohio", 66, "#0000ff")]
		Ohio = 100000081,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Oklahoma", 67)]
		Oklahoma = 100000043,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Ontario", 68)]
		Ontario = 100000044,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Oregon", 69)]
		Oregon = 100000045,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 70, "#0000ff")]
		Other = 100000086,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Palau", 71, "#0000ff")]
		Palau = 100000098,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Paris", 72)]
		Paris = 100000046,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Pensylvania", 73)]
		Pensylvania = 100000047,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Prince Edward Island", 74)]
		PrinceEdwardIsland = 100000048,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Puerto Rico", 75, "#0000ff")]
		PuertoRico = 100000097,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Quebec", 76)]
		Quebec = 100000049,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Rhode Island", 77, "#0000ff")]
		RhodeIsland = 100000082,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Samoa", 78, "#0000ff")]
		Samoa = 100000087,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Saskatchewan", 79)]
		Saskatchewan = 100000050,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Shiga", 80)]
		Shiga = 100000051,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("South Australia", 81, "#0000ff")]
		SouthAustralia = 100000089,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("South Carolina", 82)]
		SouthCarolina = 100000052,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("South Dakota", 83, "#0000ff")]
		SouthDakota = 100000083,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Surrey", 84)]
		Surrey = 100000053,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tasmania", 85, "#0000ff")]
		Tasmania = 100000092,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Tennessee", 86)]
		Tennessee = 100000054,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Texas", 87)]
		Texas = 100000055,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Utah", 88, "#0000ff")]
		Utah = 100000084,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Vermont", 89, "#0000ff")]
		Vermont = 100000085,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Victoria", 90, "#0000ff")]
		Victoria = 100000091,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Virginia", 91)]
		Virginia = 100000056,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Virgin Islands", 92, "#0000ff")]
		VirginIslands = 100000099,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Washington", 93)]
		Washington = 100000057,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Western Australia", 95, "#0000ff")]
		WesternAustralia = 100000090,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Western Cape", 96)]
		WesternCape = 100000059,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("West Virginia", 94)]
		WestVirginia = 100000058,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Wisconsin", 97)]
		Wisconsin = 100000060,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Wyoming", 98)]
		Wyoming = 100000061,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Yukon", 99)]
		Yukon = 100000062,
	}
}
#pragma warning restore CS1591
