#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_GetCities")]
	public partial class VSd_GetCitiesRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string City = "City";
			public const string Country = "Country";
			public const string Province = "Province";
			public const string TopCount = "TopCount";
		}
		
		public const string ActionLogicalName = "vsd_GetCities";
		
		public string City
		{
			get
			{
				if (this.Parameters.Contains("City"))
				{
					return ((string)(this.Parameters["City"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["City"] = value;
			}
		}
		
		public string Country
		{
			get
			{
				if (this.Parameters.Contains("Country"))
				{
					return ((string)(this.Parameters["Country"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Country"] = value;
			}
		}
		
		public string Province
		{
			get
			{
				if (this.Parameters.Contains("Province"))
				{
					return ((string)(this.Parameters["Province"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["Province"] = value;
			}
		}
		
		public int TopCount
		{
			get
			{
				if (this.Parameters.Contains("TopCount"))
				{
					return ((int)(this.Parameters["TopCount"]));
				}
				else
				{
					return default(int);
				}
			}
			set
			{
				this.Parameters["TopCount"] = value;
			}
		}
		
		public VSd_GetCitiesRequest()
		{
			this.RequestName = "vsd_GetCities";
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_GetCities")]
	public partial class VSd_GetCitiesResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string CityCollection = "CityCollection";
			public const string CountryCollection = "CountryCollection";
			public const string ProvinceCollection = "ProvinceCollection";
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "vsd_GetCities";
		
		public VSd_GetCitiesResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection CityCollection
		{
			get
			{
				if (this.Results.Contains("CityCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["CityCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["CityCollection"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection CountryCollection
		{
			get
			{
				if (this.Results.Contains("CountryCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["CountryCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["CountryCollection"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection ProvinceCollection
		{
			get
			{
				if (this.Results.Contains("ProvinceCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Results["ProvinceCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Results["ProvinceCollection"] = value;
			}
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
