#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_SubmitReimbursementInvoice")]
	public partial class VSd_SubmitReimbursementInvoiceRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CaseId = "CaseId";
			public const string Invoice = "Invoice";
			public const string ContactInfoComments = "ContactInfoComments";
			public const string TravelInfoCollection = "TravelInfoCollection";
			public const string TransportationExpenseCollection = "TransportationExpenseCollection";
			public const string AccommodationExpenseCollection = "AccommodationExpenseCollection";
			public const string MealExpenseCollection = "MealExpenseCollection";
			public const string OtherExpenseCollection = "OtherExpenseCollection";
			public const string ChildCareExpenseCollection = "ChildCareExpenseCollection";
			public const string DocumentCollection = "DocumentCollection";
		}
		
		public const string ActionLogicalName = "vsd_SubmitReimbursementInvoice";
		
		public Microsoft.Xrm.Sdk.EntityReference CaseId
		{
			get
			{
				if (this.Parameters.Contains("CaseId"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["CaseId"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["CaseId"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.Entity Invoice
		{
			get
			{
				if (this.Parameters.Contains("Invoice"))
				{
					return ((Microsoft.Xrm.Sdk.Entity)(this.Parameters["Invoice"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Entity);
				}
			}
			set
			{
				this.Parameters["Invoice"] = value;
			}
		}
		
		public string ContactInfoComments
		{
			get
			{
				if (this.Parameters.Contains("ContactInfoComments"))
				{
					return ((string)(this.Parameters["ContactInfoComments"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["ContactInfoComments"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection TravelInfoCollection
		{
			get
			{
				if (this.Parameters.Contains("TravelInfoCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["TravelInfoCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["TravelInfoCollection"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection TransportationExpenseCollection
		{
			get
			{
				if (this.Parameters.Contains("TransportationExpenseCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["TransportationExpenseCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["TransportationExpenseCollection"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection AccommodationExpenseCollection
		{
			get
			{
				if (this.Parameters.Contains("AccommodationExpenseCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["AccommodationExpenseCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["AccommodationExpenseCollection"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection MealExpenseCollection
		{
			get
			{
				if (this.Parameters.Contains("MealExpenseCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["MealExpenseCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["MealExpenseCollection"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection OtherExpenseCollection
		{
			get
			{
				if (this.Parameters.Contains("OtherExpenseCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["OtherExpenseCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["OtherExpenseCollection"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection ChildCareExpenseCollection
		{
			get
			{
				if (this.Parameters.Contains("ChildcareExpenseCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["ChildcareExpenseCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["ChildcareExpenseCollection"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityCollection DocumentCollection
		{
			get
			{
				if (this.Parameters.Contains("DocumentCollection"))
				{
					return ((Microsoft.Xrm.Sdk.EntityCollection)(this.Parameters["DocumentCollection"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityCollection);
				}
			}
			set
			{
				this.Parameters["DocumentCollection"] = value;
			}
		}
		
		public VSd_SubmitReimbursementInvoiceRequest()
		{
			this.RequestName = "vsd_SubmitReimbursementInvoice";
			this.CaseId = default(Microsoft.Xrm.Sdk.EntityReference);
			this.Invoice = default(Microsoft.Xrm.Sdk.Entity);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_SubmitReimbursementInvoice")]
	public partial class VSd_SubmitReimbursementInvoiceResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string IsSuccess = "IsSuccess";
			public const string Result = "Result";
		}
		
		public const string ActionLogicalName = "vsd_SubmitReimbursementInvoice";
		
		public VSd_SubmitReimbursementInvoiceResponse()
		{
		}
		
		public bool IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((bool)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsSuccess"] = value;
			}
		}
		
		public string Result
		{
			get
			{
				if (this.Results.Contains("Result"))
				{
					return ((string)(this.Results["Result"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Results["Result"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
