#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("vsd_CheckVSUCase")]
	public partial class VSd_CheckVSuCaseRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public static class Fields
		{
			public const string CaseNumber = "CaseNumber";
			public const string FirstName = "FirstName";
			public const string LastName = "LastName";
			public const string Birthdate = "Birthdate";
		}
		
		public const string ActionLogicalName = "vsd_CheckVSUCase";
		
		public string CaseNumber
		{
			get
			{
				if (this.Parameters.Contains("CaseNumber"))
				{
					return ((string)(this.Parameters["CaseNumber"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["CaseNumber"] = value;
			}
		}
		
		public string FirstName
		{
			get
			{
				if (this.Parameters.Contains("FirstName"))
				{
					return ((string)(this.Parameters["FirstName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["FirstName"] = value;
			}
		}
		
		public string LastName
		{
			get
			{
				if (this.Parameters.Contains("LastName"))
				{
					return ((string)(this.Parameters["LastName"]));
				}
				else
				{
					return default(string);
				}
			}
			set
			{
				this.Parameters["LastName"] = value;
			}
		}
		
		public System.DateTime Birthdate
		{
			get
			{
				if (this.Parameters.Contains("BirthDate"))
				{
					return ((System.DateTime)(this.Parameters["BirthDate"]));
				}
				else
				{
					return default(System.DateTime);
				}
			}
			set
			{
				this.Parameters["BirthDate"] = value;
			}
		}
		
		public VSd_CheckVSuCaseRequest()
		{
			this.RequestName = "vsd_CheckVSUCase";
			this.CaseNumber = default(string);
			this.FirstName = default(string);
			this.LastName = default(string);
			this.Birthdate = default(System.DateTime);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/vsd/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("vsd_CheckVSUCase")]
	public partial class VSd_CheckVSuCaseResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public static class Fields
		{
			public const string CaseId = "CaseId";
			public const string IsSuccess = "IsSuccess";
		}
		
		public const string ActionLogicalName = "vsd_CheckVSUCase";
		
		public VSd_CheckVSuCaseResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.EntityReference CaseId
		{
			get
			{
				if (this.Results.Contains("CaseId"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Results["CaseId"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Results["CaseId"] = value;
			}
		}
		
		public bool IsSuccess
		{
			get
			{
				if (this.Results.Contains("IsSuccess"))
				{
					return ((bool)(this.Results["IsSuccess"]));
				}
				else
				{
					return default(bool);
				}
			}
			set
			{
				this.Results["IsSuccess"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
