/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */
import { HttpClient, HttpHeaders } from '@angular/common/http';
import type { HttpContext, HttpEvent, HttpParams, HttpResponse as AngularHttpResponse } from '@angular/common/http';

import { Injectable, inject } from '@angular/core';

import { Observable } from 'rxjs';

import type { CheckCaseDto, ReimbursementCaseDto } from '../../model';

interface HttpClientOptions {
  readonly headers?: HttpHeaders | Record<string, string | string[]>;
  readonly context?: HttpContext;
  readonly params?: HttpParams | Record<string, string | number | boolean | Array<string | number | boolean>>;
  readonly reportProgress?: boolean;
  readonly withCredentials?: boolean;
  readonly credentials?: RequestCredentials;
  readonly keepalive?: boolean;
  readonly priority?: RequestPriority;
  readonly cache?: RequestCache;
  readonly mode?: RequestMode;
  readonly redirect?: RequestRedirect;
  readonly referrer?: string;
  readonly integrity?: string;
  readonly referrerPolicy?: ReferrerPolicy;
  readonly transferCache?: { includeHeaders?: string[] } | boolean;
}

@Injectable({ providedIn: 'root' })
export class ReimbursementService {
  private readonly http = inject(HttpClient);
  postApiReimbursement<TData = void>(
    reimbursementCaseDto: ReimbursementCaseDto,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  postApiReimbursement<TData = void>(
    reimbursementCaseDto: ReimbursementCaseDto,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  postApiReimbursement<TData = void>(
    reimbursementCaseDto: ReimbursementCaseDto,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  postApiReimbursement<TData = void>(
    reimbursementCaseDto: ReimbursementCaseDto,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/vsuwebforms/api/Reimbursement`, reimbursementCaseDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/vsuwebforms/api/Reimbursement`, reimbursementCaseDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.post<TData>(`/vsuwebforms/api/Reimbursement`, reimbursementCaseDto, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
  postApiReimbursementCheckCase<TData = void>(
    checkCaseDto: CheckCaseDto,
    options?: HttpClientOptions & { observe?: 'body' }
  ): Observable<TData>;
  postApiReimbursementCheckCase<TData = void>(
    checkCaseDto: CheckCaseDto,
    options?: HttpClientOptions & { observe: 'events' }
  ): Observable<HttpEvent<TData>>;
  postApiReimbursementCheckCase<TData = void>(
    checkCaseDto: CheckCaseDto,
    options?: HttpClientOptions & { observe: 'response' }
  ): Observable<AngularHttpResponse<TData>>;
  postApiReimbursementCheckCase<TData = void>(
    checkCaseDto: CheckCaseDto,
    options?: HttpClientOptions & { observe?: 'body' | 'events' | 'response' }
  ): Observable<TData | HttpEvent<TData> | AngularHttpResponse<TData>> {
    if (options?.observe === 'events') {
      return this.http.post<TData>(`/vsuwebforms/api/Reimbursement/check_case`, checkCaseDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'events'
      });
    }

    if (options?.observe === 'response') {
      return this.http.post<TData>(`/vsuwebforms/api/Reimbursement/check_case`, checkCaseDto, {
        ...(options as Omit<NonNullable<typeof options>, 'observe'>),
        observe: 'response'
      });
    }

    return this.http.post<TData>(`/vsuwebforms/api/Reimbursement/check_case`, checkCaseDto, {
      ...(options as Omit<NonNullable<typeof options>, 'observe'>),
      observe: 'body'
    });
  }
}
