/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */
import type { Application } from './application';
import type { CourtInfo } from './courtInfo';
import type { Offence } from './offence';
import type { Participant } from './participant';
import type { TravelInfo } from './travelInfo';

export interface ApplicationData {
  application?: Application;
  /** @nullable */
  courtInfoCollection?: CourtInfo[] | null;
  /** @nullable */
  providerCollection?: Participant[] | null;
  /** @nullable */
  offenceCollection?: Offence[] | null;
  /** @nullable */
  travelInfoCollection?: TravelInfo[] | null;
}
