/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface ApplicationDto {
  vsuApplicationType?: number;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  victimFirstName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  victimMiddleName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  victimLastName?: string | null;
  /** @nullable */
  victimBirthDate?: string | null;
  /** @nullable */
  victimGenderCode?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  victimGenderText?: string | null;
  /** @nullable */
  victimPronouns?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  victimPronounText?: string | null;
  /** @nullable */
  victimPrimaryRaceEthnicity?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  victimPrimaryRaceEthnicityText?: string | null;
  /** @nullable */
  victimIndigenous?: number | null;
  vsuApplicantType?: number;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuApplicantTypeOther?: string | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsuOffencesComments?: string | null;
  /** @nullable */
  vsuDecision1ImpactToOutcome?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsuDecision1Comments?: string | null;
  /** @nullable */
  vsuDecision2TravelOver100Km?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsuDecision2Comments?: string | null;
  /** @nullable */
  vsuDecision3NoOtherFundingSource?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsuDecision3Comments?: string | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsuAdditionalComments?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  relationshipToVictim?: string | null;
  /** @nullable */
  vsuVictimTravelFundApplicationSubmitted?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuVtfAppSubmittedUnknownComments?: string | null;
  /** @nullable */
  vsuOtherFamilyMembersApplyingToVtf?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuOtherFamilyMembersVtfOtherComments?: string | null;
  /** @nullable */
  vsuVswComments?: string | null;
  /** @nullable */
  vsuCostsCoveredByVsp?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsuVspComments?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsuManagerFirstName?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsuManagerLastName?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsuOrganizationAgencyName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuManagerPhone?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuManagerEmail?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsFirstName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsMiddleName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsLastName?: string | null;
  /** @nullable */
  applicantsGenderCode?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  genderIdentityText?: string | null;
  /** @nullable */
  pronouns?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  pronounText?: string | null;
  /** @nullable */
  applicantsBirthDate?: string | null;
  /** @nullable */
  primaryRaceEthnicity?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  primaryRaceEthnicityText?: string | null;
  /** @nullable */
  indigenous?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsPreferredLanguage?: string | null;
  /** @nullable */
  applicantsInterpreterNeeded?: number | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  applicantsPrimaryAddressLine1?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  applicantsPrimaryAddressLine2?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsPrimaryCity?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsPrimaryProvince?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsPrimaryCountry?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  applicantsPrimaryPostalCode?: string | null;
  /** @nullable */
  vsuOkToSendMail?: number | null;
  /** @nullable */
  vsuMethodOfContact1Type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuMethodOfContact1Number?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuMethodOfContact1Ext?: string | null;
  /** @nullable */
  vsuMethodOfContact1LeaveDetailedMessage?: number | null;
  /** @nullable */
  vsuMethodOfContact2Type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuMethodOfContact2Number?: string | null;
  /** @nullable */
  vsuMethodOfContact2LeaveDetailedMessage?: number | null;
  /** @nullable */
  vsuMethodOfContact3Type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuMethodOfContact3Number?: string | null;
  /** @nullable */
  vsuMethodOfContact3LeaveDetailedMessage?: number | null;
  /** @nullable */
  vsuNotificationTo?: number | null;
  /** @nullable */
  vsuDiscussVtfAppWithVsp?: number | null;
  /** @nullable */
  vsuSignificantCourtUpdates?: number | null;
  /** @nullable */
  vsuFinalCourtResults?: number | null;
  /** @nullable */
  vsuUpdatesOnAllCriminalCourtAppearances?: number | null;
  /** @nullable */
  vsuCriminalCourtOrdersIssued?: number | null;
  /** @nullable */
  vsuBcCorrectionsInformation?: number | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsuNotificationAdditionalComments?: string | null;
  /** @nullable */
  vsuTravelExpenseRequest?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuTravelExpenseRequestTransportOther?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuTravelExpenseRequestOther?: string | null;
  /** @nullable */
  vsuPurposeOfTravel?: string | null;
  /** @nullable */
  vsuTravelPeriodFrom?: string | null;
  /** @nullable */
  vsuTravelPeriodTo?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsuAdditionalTravelComments?: string | null;
  /** @nullable */
  vsuInfoShareCscpBc?: number | null;
  /** @nullable */
  vsuInfoShareVsu?: number | null;
  /** @nullable */
  vsuInfoShareVsw?: number | null;
  /** @nullable */
  declarationVerified?: number | null;
  /**
   * @minLength 0
   * @maxLength 150
   * @nullable
   */
  declarationFullName?: string | null;
  /** @nullable */
  declarationDate?: string | null;
  /** @nullable */
  applicantsSignature?: string | null;
}
