/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface ApplicationDto {
  applicationType?: number;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  victimFirstName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  victimMiddleName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_otherfirstname?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_otherlastname?: string | null;
  /** @nullable */
  vsd_dateofnamechange?: string | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_victimgendertext?: string | null;
  /** @nullable */
  vsd_victimpronouns?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_victimpronountext?: string | null;
  /** @nullable */
  vsd_victimprimaryraceethnicity?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_victimprimaryraceethnicitytext?: string | null;
  /** @nullable */
  vsd_victimindigenous?: number | null;
  vsd_vsu_applicanttype?: number;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_applicanttypeother?: string | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_vsu_offencescomments?: string | null;
  /** @nullable */
  vsd_vsu_decision1impacttooutcome?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_vsu_decision1comments?: string | null;
  /** @nullable */
  vsd_vsu_decision2travelover100km?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_vsu_decision2comments?: string | null;
  /** @nullable */
  vsd_vsu_decision3nootherfundingsource?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_vsu_decision3comments?: string | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_vsu_additionalcomments?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_vtfappsubmittedunknowncomments?: string | null;
  /** @nullable */
  vsd_vsu_otherfamilymembersapplyingtovtf?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_otherfamilymembersvtfothercomments?: string | null;
  /** @nullable */
  vsd_vsu_vswcomments?: string | null;
  /** @nullable */
  vsd_vsu_costscoveredbyvsp?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_vsu_vspcomments?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsd_vsu_managerfirstname?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsd_vsu_managerlastname?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsd_vsu_organizationagencyname?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_managerphone?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_manageremail?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_applicantsfirstname?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_applicantsmiddlename?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_applicantslastname?: string | null;
  /** @nullable */
  vsd_applicantsmaritalstatus?: number | null;
  /** @nullable */
  vsd_applicantsgendercode?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_genderidentitytext?: string | null;
  /** @nullable */
  vsd_pronouns?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_pronountext?: string | null;
  /** @nullable */
  vsd_applicantsbirthdate?: string | null;
  /** @nullable */
  vsd_primaryraceethnicity?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_primaryraceethnicitytext?: string | null;
  /** @nullable */
  vsd_indigenous?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_applicantspreferredlanguage?: string | null;
  /** @nullable */
  vsd_applicantsinterpreterneeded?: number | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsd_applicantsprimaryaddressline1?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsd_applicantsprimaryaddressline2?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_applicantsprimarycity?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_applicantsprimaryprovince?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_applicantsprimarycountry?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  vsd_applicantsprimarypostalcode?: string | null;
  /** @nullable */
  vsd_vsu_oktosendmail?: number | null;
  /** @nullable */
  vsd_vsu_methodofcontact1type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_methodofcontact1number?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_methodofcontact1ext?: string | null;
  /** @nullable */
  vsd_vsu_methodofcontact1leavedetailedmessage?: number | null;
  /** @nullable */
  vsd_vsu_methodofcontact2type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_methodofcontact2number?: string | null;
  /** @nullable */
  vsd_vsu_methodofcontact2leavedetailedmessage?: number | null;
  /** @nullable */
  vsd_vsu_methodofcontact3type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_methodofcontact3number?: string | null;
  /** @nullable */
  vsd_vsu_methodofcontact3leavedetailedmessage?: number | null;
  /** @nullable */
  vsd_vsu_notificationto?: number | null;
  /** @nullable */
  vsd_vsu_discussvtfappwithvsp?: number | null;
  /** @nullable */
  vsd_vsu_significantcourtupdates?: number | null;
  /** @nullable */
  vsd_vsu_finalcourtresults?: number | null;
  /** @nullable */
  vsd_vsu_updatesonallcriminalcourtappearances?: number | null;
  /** @nullable */
  vsd_vsu_criminalcourtordersissued?: number | null;
  /** @nullable */
  vsd_vsu_bccorrectionsinformation?: number | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsd_vsu_notificationadditionalcomments?: string | null;
  /** @nullable */
  vsd_vsu_travelexpenserequest_03?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_travelexpenserequesttransportother?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_travelexpenserequestother?: string | null;
  /** @nullable */
  vsd_vsu_purposeoftravel?: string | null;
  /** @nullable */
  vsd_vsu_travelperiodfrom?: string | null;
  /** @nullable */
  vsd_vsu_travelperiodto?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsd_vsu_additionaltravelcomments?: string | null;
  /** @nullable */
  vsd_vsu_infosharecscpbc?: number | null;
  /** @nullable */
  vsd_vsu_infosharevsu?: number | null;
  /** @nullable */
  vsd_vsu_infosharevsw?: number | null;
  /** @nullable */
  vsd_declarationverified?: number | null;
  /**
   * @minLength 0
   * @maxLength 150
   * @nullable
   */
  vsd_declarationfullname?: string | null;
  /** @nullable */
  vsd_declarationdate?: string | null;
  /** @nullable */
  vsd_applicantssignature?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  relationshipToVictim?: string | null;
  /** @nullable */
  victimTravelFundApplicationSubmitted?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  victimLastName?: string | null;
  /** @nullable */
  victimBirthDate?: string | null;
  /** @nullable */
  victimGenderCode?: number | null;
}
