/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface Case {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /** @nullable */
  incidentid?: string | null;
  /** @nullable */
  vsd_courtdate?: string | null;
  /** @nullable */
  vsd_purposeoftravel?: string | null;
  /** @nullable */
  vsd_travelperiodfrom?: string | null;
  /** @nullable */
  vsd_travelperiodto?: string | null;
}
