/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface CheckCaseDto {
  /** @nullable */
  caseNumber?: string | null;
  /** @nullable */
  firstName?: string | null;
  /** @nullable */
  lastName?: string | null;
  /** @nullable */
  birthDate?: string | null;
}
