/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface CourtInfo {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_courtfilenumber?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_courtlocation?: string | null;
}
