/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface DocumentDto {
  /**
   * @minLength 0
   * @maxLength 225
   * @nullable
   */
  vsd_filename?: string | null;
  /**
   * @minLength 0
   * @maxLength 1073741823
   * @nullable
   */
  vsd_body?: string | null;
  /**
   * @minLength 0
   * @maxLength 2000
   * @nullable
   */
  vsd_subject?: string | null;
}
