/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface InvoiceLineDetail {
  /** @nullable */
  readonly fortunecookietype?: string | null;
  vsd_vsu_expensetype?: number;
  /** @nullable */
  vsd_vsu_transportationtype?: number | null;
  /** @nullable */
  vsd_vsu_mileage?: number | null;
  /** @nullable */
  vsd_amountsimple?: number | null;
  /** @nullable */
  vsd_vsu_other?: string | null;
  /** @nullable */
  vsd_vsu_number?: number | null;
  /** @nullable */
  vsd_vsu_dailyroomrate?: number | null;
  /** @nullable */
  vsd_vsu_childage?: number | null;
  /** @nullable */
  vsd_vsu_childcarestartdate?: string | null;
  /** @nullable */
  vsd_vsu_childcareenddate?: string | null;
  /**
   * @minLength 0
   * @maxLength 160
   * @nullable
   */
  vsd_vsu_childcareproviderfirstname?: string | null;
  /**
   * @minLength 0
   * @maxLength 160
   * @nullable
   */
  vsd_childcareproviderlastname?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  vsd_vsu_childcareproviderphoneno?: string | null;
}
