/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface InvoiceDto {
  /** @nullable */
  claimantContactInfoChanged?: number | null;
  /** @nullable */
  signatureDate?: string | null;
  /** @nullable */
  signature?: string | null;
  /** @nullable */
  declarationSignature?: string | null;
}
