/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface Invoice {
  /** @nullable */
  vsd_vsu_claimantcontactinfochanged?: number | null;
  /** @nullable */
  vsd_vsu_signaturedate?: string | null;
  /** @nullable */
  vsd_signature?: string | null;
  /** @nullable */
  vsd_vsu_declarationsignature?: string | null;
}
