/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface OffenceDto {
  /** @nullable */
  vsd_offenseid?: string | null;
}
