/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface ParticipantDto {
  /**
   * @minLength 0
   * @maxLength 160
   * @nullable
   */
  vsd_firstname?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_middlename?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_lastname?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_companyname?: string | null;
  /**
   * @minLength 0
   * @maxLength 400
   * @nullable
   */
  vsd_name?: string | null;
  /** @nullable */
  vsd_birthdate?: string | null;
  /** @nullable */
  vsd_gender?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_genderidentitytext?: string | null;
  /** @nullable */
  vsd_pronouns?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_pronountext?: string | null;
  /** @nullable */
  vsd_primaryraceethnicity?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vsd_primaryraceethnicitytext?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsd_phonenumber?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_mainphoneextension?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsd_addressline1?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  vsd_addressline2?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_city?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_province?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  vsd_postalcode?: string | null;
  /** @nullable */
  vsd_vsu_oktosendmail?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_email?: string | null;
  /**
   * @minLength 0
   * @maxLength 150
   * @nullable
   */
  vsd_relationship1?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_relationship1other?: string | null;
  /**
   * @minLength 0
   * @maxLength 150
   * @nullable
   */
  vsd_relationship2?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_relationship2other?: string | null;
  /** @nullable */
  vsd_vsu_methodofcontact1type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_methodofcontact1number?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_methodofcontact1ext?: string | null;
  /** @nullable */
  vsd_vsu_methodofcontact1leavedetailedmessage?: number | null;
  /** @nullable */
  vsd_vsu_methodofcontact2type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_methodofcontact2number?: string | null;
  /** @nullable */
  vsd_vsu_methodofcontact2leavedetailedmessage?: number | null;
  /** @nullable */
  vsd_vsu_methodofcontact3type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_vsu_methodofcontact3number?: string | null;
  /** @nullable */
  vsd_vsu_methodofcontact3leavedetailedmessage?: number | null;
}
