/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface ParticipantDto {
  /**
   * @minLength 0
   * @maxLength 160
   * @nullable
   */
  firstName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  middleName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  lastName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  companyName?: string | null;
  /**
   * @minLength 0
   * @maxLength 400
   * @nullable
   */
  name?: string | null;
  /** @nullable */
  birthDate?: string | null;
  /** @nullable */
  gender?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  genderIdentityText?: string | null;
  /** @nullable */
  pronouns?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  pronounText?: string | null;
  /** @nullable */
  primaryRaceEthnicity?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  primaryRaceEthnicityText?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  phoneNumber?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  mainPhoneExtension?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  addressLine1?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  addressLine2?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  city?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  province?: string | null;
  /**
   * @minLength 0
   * @maxLength 20
   * @nullable
   */
  postalCode?: string | null;
  /** @nullable */
  vsuOkToSendMail?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  email?: string | null;
  /**
   * @minLength 0
   * @maxLength 150
   * @nullable
   */
  relationship1?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  relationship1Other?: string | null;
  /**
   * @minLength 0
   * @maxLength 150
   * @nullable
   */
  relationship2?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  relationship2Other?: string | null;
  /** @nullable */
  vsuMethodOfContact1Type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuMethodOfContact1Number?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuMethodOfContact1Ext?: string | null;
  /** @nullable */
  vsuMethodOfContact1LeaveDetailedMessage?: number | null;
  /** @nullable */
  vsuMethodOfContact2Type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuMethodOfContact2Number?: string | null;
  /** @nullable */
  vsuMethodOfContact2LeaveDetailedMessage?: number | null;
  /** @nullable */
  vsuMethodOfContact3Type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsuMethodOfContact3Number?: string | null;
  /** @nullable */
  vsuMethodOfContact3LeaveDetailedMessage?: number | null;
}
