/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */
import type { Case } from './case';
import type { DocumentCollection } from './documentCollection';
import type { Invoice } from './invoice';
import type { InvoiceLineDetail } from './invoiceLineDetail';
import type { TravelInfo } from './travelInfo';

export interface ReimbursementData {
  caseId?: Case;
  /** @nullable */
  contactInfoComments?: string | null;
  invoice?: Invoice;
  /** @nullable */
  travelInfoCollection?: TravelInfo[] | null;
  /** @nullable */
  transportationExpenseCollection?: InvoiceLineDetail[] | null;
  /** @nullable */
  accommodationExpenseCollection?: InvoiceLineDetail[] | null;
  /** @nullable */
  mealExpenseCollection?: InvoiceLineDetail[] | null;
  /** @nullable */
  childcareExpenseCollection?: InvoiceLineDetail[] | null;
  /** @nullable */
  otherExpenseCollection?: InvoiceLineDetail[] | null;
  /** @nullable */
  documentCollection?: DocumentCollection[] | null;
}
