/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface TravelInfoDto {
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  courtFileNumber?: string | null;
  /** @nullable */
  courtDate?: string | null;
  /**
   * @minLength 0
   * @maxLength 1000
   * @nullable
   */
  purposeOfTravel?: string | null;
  /** @nullable */
  travelPeriodFrom?: string | null;
  /** @nullable */
  travelPeriodTo?: string | null;
}
