/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface TravelInfoDto {
  /** @nullable */
  vsd_courtdate?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  vsd_courtfilenumber_text?: string | null;
  /**
   * @minLength 0
   * @maxLength 1000
   * @nullable
   */
  vsd_purposeoftravel?: string | null;
  /** @nullable */
  vsd_travelperiodfrom?: string | null;
  /** @nullable */
  vsd_travelperiodto?: string | null;
}
