/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */
import type { CourtInfoDto } from './courtInfoDto';
import type { DocumentDto } from './documentDto';
import type { OffenceDto } from './offenceDto';
import type { ParticipantDto } from './participantDto';
import type { TravelInfoDto } from './travelInfoDto';
import type { VtfReimbursementApplicationDto } from './vtfReimbursementApplicationDto';

export interface VtfReimbursementApplicationDataDto {
  application?: VtfReimbursementApplicationDto;
  /** @nullable */
  courtInfoCollection?: CourtInfoDto[] | null;
  /** @nullable */
  providerCollection?: ParticipantDto[] | null;
  /** @nullable */
  offenceCollection?: OffenceDto[] | null;
  /** @nullable */
  travelInfoCollection?: TravelInfoDto[] | null;
  /** @nullable */
  documentCollection?: DocumentDto[] | null;
}
