/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * VSU API
 * API for the Victim Services Unit Application (VSU) application
 * OpenAPI spec version: v1
 */

export interface VtfReimbursementApplicationDto {
  applicationType?: number;
  /**
   * @minLength 0
   * @maxLength 100
   */
  victimFirstName: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  victimMiddleName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   */
  victimLastName: string;
  victimBirthDate: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  otherFirstname?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  otherLastname?: string | null;
  /** @nullable */
  dateOfNameChange?: string | null;
  /** @nullable */
  victimGenderCode?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  victimGenderText?: string | null;
  /** @nullable */
  victimPronouns?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  victimPronounText?: string | null;
  /** @nullable */
  victimPrimaryRaceEthnicity?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  victimPrimaryRaceEthnicityText?: string | null;
  /** @nullable */
  victimIndigenous?: number | null;
  applicantType: number;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantTypeOther?: string | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  offencesComments?: string | null;
  /** @nullable */
  decision1ImpactToOutcome?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  decision1Comments?: string | null;
  /** @nullable */
  decision2TravelOver100KM?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  decision2Comments?: string | null;
  /** @nullable */
  decision3NoOtherFundingSource?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  decision3Comments?: string | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  additionalComments?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  relationshipToVictim?: string | null;
  /** @nullable */
  victimTravelFundApplicationSubmitted?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  victimTravelFundApplicationSubmittedUnknownComments?: string | null;
  /** @nullable */
  otherFamilyMembersApplyingToVTF?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  otherFamilyMembersVTFOtherComments?: string | null;
  /** @nullable */
  vswComments?: string | null;
  /** @nullable */
  costsCoveredByVSP?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  vspComments?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  managerFirstName?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  managerLastName?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  organizationAgencyName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  managerPhone?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  managerEmail?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   */
  applicantsFirstName: string;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsMiddleName?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   */
  applicantsLastName: string;
  /** @nullable */
  applicantsMaritalStatus?: number | null;
  /** @nullable */
  applicantsGenderCode?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsGenderIdentityText?: string | null;
  /** @nullable */
  applicantsPronouns?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsPronounText?: string | null;
  applicantsBirthDate: string;
  /** @nullable */
  applicantsPrimaryRaceEthnicity?: number | null;
  /**
   * @minLength 0
   * @maxLength 500
   * @nullable
   */
  applicantsPrimaryRaceEthnicityText?: string | null;
  /** @nullable */
  applicantsIndigenous?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsPreferredLanguage?: string | null;
  /** @nullable */
  applicantsInterpreterNeeded?: number | null;
  /**
   * @minLength 0
   * @maxLength 250
   */
  applicantsPrimaryAddressLine1: string;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  applicantsPrimaryAddressLine2?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   */
  applicantsPrimaryCity: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  applicantsPrimaryProvince: string;
  /**
   * @minLength 0
   * @maxLength 100
   */
  applicantsPrimaryCountry: string;
  /**
   * @minLength 0
   * @maxLength 20
   */
  applicantsPrimaryPostalCode: string;
  /** @nullable */
  applicantsOkToSendMail?: number | null;
  /** @nullable */
  applicantsMethodOfContact1Type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsMethodOfContact1Number?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsMethodOfContact1Ext?: string | null;
  /** @nullable */
  applicantsMethodOfContact1LeaveDetailedMessage?: number | null;
  /** @nullable */
  applicantsMethodOfContact2Type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsMethodOfContact2Number?: string | null;
  /** @nullable */
  applicantsMethodOfContact2LeaveDetailedMessage?: number | null;
  /** @nullable */
  applicantsMethodOfContact3Type?: number | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsMethodOfContact3Number?: string | null;
  /** @nullable */
  applicantsMethodOfContact3LeaveDetailedMessage?: number | null;
  /** @nullable */
  applicantsNotificationTo?: number | null;
  /** @nullable */
  applicantsDiscussVTFAppWithVSP?: number | null;
  /** @nullable */
  applicantsSignificantCourtUpdates?: number | null;
  /** @nullable */
  applicantsFinalCourtResults?: number | null;
  /** @nullable */
  applicantsUpdatesOnAllCriminalCourtAppearances?: number | null;
  /** @nullable */
  applicantsCriminalCourtOrdersIssued?: number | null;
  /** @nullable */
  applicantsBCCorrectionsInformation?: number | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  applicantsNotificationAdditionalComments?: string | null;
  /** @nullable */
  applicantsTravelExpenseRequest03?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsTravelExpenseRequestTransportOther?: string | null;
  /**
   * @minLength 0
   * @maxLength 100
   * @nullable
   */
  applicantsTravelExpenseRequestOther?: string | null;
  /** @nullable */
  applicantsPurposeOfTravel?: string | null;
  /** @nullable */
  applicantsTravelPeriodFrom?: string | null;
  /** @nullable */
  applicantsTravelPeriodTo?: string | null;
  /**
   * @minLength 0
   * @maxLength 250
   * @nullable
   */
  applicantsAdditionalTravelComments?: string | null;
  /** @nullable */
  applicantsInfoShareCSCPBC?: number | null;
  /** @nullable */
  applicantsInfoShareVSU?: number | null;
  /** @nullable */
  applicantsInfoShareVSW?: number | null;
  /** @nullable */
  applicantsDeclarationVerified?: number | null;
  /**
   * @minLength 0
   * @maxLength 150
   * @nullable
   */
  applicantsDeclarationFullName?: string | null;
  /** @nullable */
  applicantsDeclarationDate?: string | null;
  /** @nullable */
  applicantsSignature?: string | null;
}
