export interface IDynamicsContact {
    address1_city: string,
    address1_country: string,
    address1_line1: string,
    address1_line2: string,
    address1_line3: string,
    address1_postalcode: string,
    address1_stateorprovince: string,
    contactid: string,
    emailaddress1: string,
    fax: string,
    firstname: string,
    gendercode: number,
    lastname: string,
    middlename: string,
    mobilephone: string,
    preferredcontactmethodcode: number,
    telephone1: string,
    vsd_dateofbirth: Date,
}