#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataverseModel
{
	
	
	/// <summary>
	/// Status of the Invoice Line Detail
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum VSd_InvoiceLineDetail_StateCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Invoice Line Detail
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum VSd_InvoiceLineDetail_StatusCode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Active", 0)]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Inactive", 1)]
		Inactive = 2,
	}
	
	/// <summary>
	/// The type of counselling session.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum VSd_InvoiceLineDetail_VSd_CVAp_CounsellingType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Counselling Session", 0, "#0000ff")]
		CounsellingSession = 100000000,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Court Support Counselling", 1, "#0000ff")]
		CourtSupportCounselling = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Psycho-educational Session", 2, "#0000ff")]
		PsychoEducationalSession = 100000002,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum VSd_InvoiceLineDetail_VSd_TaxExemption
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("All Tax", 0, "#0000ff")]
		AllTax = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("GST only", 2, "#0000ff")]
		GstOnly = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("No Tax", 3, "#0000ff")]
		NoTax = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("PST only", 1, "#0000ff")]
		PstOnly = 100000000,
	}
	
	/// <summary>
	/// Line item expense type for VSU invoices.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum VSd_InvoiceLineDetail_VSd_VSu_ExpenseType
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Accomodation", 0, "#0000ff")]
		Accomodation = 100000001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Childcare", 1, "#0000ff")]
		Childcare = 100000006,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Meal - Breakfast", 2, "#0000ff")]
		MealBreakfast = 100000002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Meal - Dinner", 3, "#0000ff")]
		MealDinner = 100000005,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Meal - Lunch", 4, "#0000ff")]
		MealLunch = 100000004,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Other", 6, "#0000ff")]
		Other = 100000003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		[OptionSetMetadataAttribute("Transportation", 5, "#0000ff")]
		Transportation = 100000000,
	}
	
	/// <summary>
	/// Invoice Line item details.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("vsd_invoicelinedetail")]
	public partial class VSd_InvoiceLineDetail : Microsoft.Xrm.Sdk.Entity
	{
		
		/// <summary>
		/// Available fields, a the time of codegen, for the vsd_invoicelinedetail entity
		/// </summary>
		public partial class Fields
		{
			public const string Business_Unit_VSd_InvoiceLineDetail = "business_unit_vsd_invoicelinedetail";
			public const string CreatedBy = "createdby";
			public const string CreatedByName = "createdbyname";
			public const string CreatedByYomiName = "createdbyyominame";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CreatedOnBehalfByName = "createdonbehalfbyname";
			public const string CreatedOnBehalfByYomiName = "createdonbehalfbyyominame";
			public const string ExchangeRate = "exchangerate";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string Lk_VSd_InvoiceLineDetail_CreatedBy = "lk_vsd_invoicelinedetail_createdby";
			public const string Lk_VSd_InvoiceLineDetail_CreatedOnBehalfBy = "lk_vsd_invoicelinedetail_createdonbehalfby";
			public const string Lk_VSd_InvoiceLineDetail_ModifiedBy = "lk_vsd_invoicelinedetail_modifiedby";
			public const string Lk_VSd_InvoiceLineDetail_ModifiedOnBehalfBy = "lk_vsd_invoicelinedetail_modifiedonbehalfby";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByName = "modifiedbyname";
			public const string ModifiedByYomiName = "modifiedbyyominame";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string ModifiedOnBehalfByName = "modifiedonbehalfbyname";
			public const string ModifiedOnBehalfByYomiName = "modifiedonbehalfbyyominame";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwnerIdName = "owneridname";
			public const string OwnerIdYomiName = "owneridyominame";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ProcessId = "processid";
			public const string StageId = "stageid";
			public const string StateCode = "statecode";
			public const string StateCodename = "statecodename";
			public const string StatusCode = "statuscode";
			public const string StatusCodename = "statuscodename";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrency_VSd_InvoiceLineDetail = "TransactionCurrency_vsd_invoicelinedetail";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TransactionCurrencyIdName = "transactioncurrencyidname";
			public const string TraversedPath = "traversedpath";
			public const string User_VSd_InvoiceLineDetail = "user_vsd_invoicelinedetail";
			public const string UtcConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string VSd_AmountCalculated = "vsd_amountcalculated";
			public const string VSd_AmountCalculated_Base = "vsd_amountcalculated_base";
			public const string VSd_AmountSimple = "vsd_amountsimple";
			public const string VSd_AmountSimple_Base = "vsd_amountsimple_base";
			public const string VSd_AttendingSupportPerson = "vsd_attendingsupportperson";
			public const string VSd_CaseId = "vsd_caseid";
			public const string VsD_CaseiDnaMe = "vsd_caseidname";
			public const string VSd_ChildCareProviderLastName = "vsd_childcareproviderlastname";
			public const string VSd_Cpu_ProgramTotal = "vsd_cpu_programtotal";
			public const string VSd_Cpu_ProgramTotal_Base = "vsd_cpu_programtotal_base";
			public const string VsD_CVaP_CounsellingRate = "vsd_cvap_counsellingrate";
			public const string VsD_CVaP_CounsellingRate_Base = "vsd_cvap_counsellingrate_base";
			public const string VSd_CVAp_CounsellingType = "vsd_cvap_counsellingtype";
			public const string VSd_CVAp_CounsellingTypeName = "vsd_cvap_counsellingtypename";
			public const string VSd_CVAp_CreateNewLineItem = "vsd_cvap_createnewlineitem";
			public const string VSd_CVAp_CreateNewLineItemName = "vsd_cvap_createnewlineitemname";
			public const string VSd_CVAp_SessionDate = "vsd_cvap_sessiondate";
			public const string VSd_CVAp_SessionDuration = "vsd_cvap_sessionduration";
			public const string VSd_DisbursementTransactionDetailId = "vsd_disbursementtransactiondetailid";
			public const string VsD_DisbursementTransactionDetailIdName = "vsd_disbursementtransactiondetailidname";
			public const string VSd_EntitlementId = "vsd_entitlementid";
			public const string VSd_EntitlementIdName = "vsd_entitlementidname";
			public const string VSd_Gst = "vsd_gst";
			public const string VSd_Gst_Base = "vsd_gst_base";
			public const string VSd_InvoiceId = "vsd_invoiceid";
			public const string VSd_InvoiceIdName = "vsd_invoiceidname";
			public const string VSd_InvoiceLineDetailId = "vsd_invoicelinedetailid";
			public const string Id = "vsd_invoicelinedetailid";
			public const string VSd_InvoiceType = "vsd_invoicetype";
			public const string VSd_InvoiceTypeName = "vsd_invoicetypename";
			public const string VSd_LineItemApproved = "vsd_lineitemapproved";
			public const string VSd_LineItemApprovedName = "vsd_lineitemapprovedname";
			public const string VSd_LineItemDescription = "vsd_lineitemdescription";
			public const string VSd_LineItemTotalAmount = "vsd_lineitemtotalamount";
			public const string VSd_LineItemTotalAmount_Base = "vsd_lineitemtotalamount_base";
			public const string VSd_LineItemTotalSimple = "vsd_lineitemtotalsimple";
			public const string VSd_LineItemTotalSimple_Base = "vsd_lineitemtotalsimple_base";
			public const string VSd_MissedSession = "vsd_missedsession";
			public const string VSd_MissedSessionName = "vsd_missedsessionname";
			public const string VSd_Name = "vsd_name";
			public const string VSd_ProgramUnit = "vsd_programunit";
			public const string VSd_ProgramUnitName = "vsd_programunitname";
			public const string VSd_ProvinceStateId = "vsd_provincestateid";
			public const string VSd_ProvinceStateIdName = "vsd_provincestateidname";
			public const string VSd_Pst = "vsd_pst";
			public const string VSd_Pst_Base = "vsd_pst_base";
			public const string VSd_TaxExemption = "vsd_taxexemption";
			public const string VSd_TaxExemptionName = "vsd_taxexemptionname";
			public const string VSd_TaxRate = "vsd_taxrate";
			public const string VSd_TaxRate2 = "vsd_taxrate2";
			public const string VSd_VSd_Invoice_VSd_InvoiceLineDetail = "vsd_vsd_invoice_vsd_invoicelinedetail";
			public const string VSd_VSd_Province_VSd_InvoiceLineDetail_ProvinceStateId = "vsd_vsd_province_vsd_invoicelinedetail_ProvinceStateId";
			public const string VSd_VSu_ChildAge = "vsd_vsu_childage";
			public const string VSd_VSu_ChildCareEndDate = "vsd_vsu_childcareenddate";
			public const string VSd_VSu_ChildCareProviderCity = "vsd_vsu_childcareprovidercity";
			public const string VSd_VSu_ChildCareProviderCountry = "vsd_vsu_childcareprovidercountry";
			public const string VSd_VSu_ChildCareProviderFirstName = "vsd_vsu_childcareproviderfirstname";
			public const string VSd_VSu_ChildCareProviderGstBusinessNumber = "vsd_vsu_childcareprovidergstbusinessnumber";
			public const string VSd_VSu_ChildCareProviderMailAddress1 = "vsd_vsu_childcareprovidermailaddress1";
			public const string VSd_VSu_ChildCareProviderMailAddress2 = "vsd_vsu_childcareprovidermailaddress2";
			public const string VSd_VSu_ChildCareProviderPhoneNo = "vsd_vsu_childcareproviderphoneno";
			public const string VSd_VSu_ChildCareProviderPostalCode = "vsd_vsu_childcareproviderpostalcode";
			public const string VSd_VSu_ChildCareProviderProvince = "vsd_vsu_childcareproviderprovince";
			public const string VSd_VSu_ChildCaRestartDate = "vsd_vsu_childcarestartdate";
			public const string VSd_VSu_DailyRoomRate = "vsd_vsu_dailyroomrate";
			public const string VSd_VSu_DailyRoomRate_Base = "vsd_vsu_dailyroomrate_base";
			public const string VSd_VSu_ExpenseType = "vsd_vsu_expensetype";
			public const string VSd_VSu_ExpenseTypeName = "vsd_vsu_expensetypename";
			public const string VSd_VSu_Mileage = "vsd_vsu_mileage";
			public const string VSd_VSu_Number = "vsd_vsu_number";
			public const string VSd_VSu_Other = "vsd_vsu_other";
			public const string VSd_VSu_TransportationType = "vsd_vsu_transportationtype";
			public const string VSd_VSu_TransportationTypeName = "vsd_vsu_transportationtypename";
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public VSd_InvoiceLineDetail(System.Guid id) : 
				base(EntityLogicalName, id)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public VSd_InvoiceLineDetail(string keyName, object keyValue) : 
				base(EntityLogicalName, keyName, keyValue)
		{
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		public VSd_InvoiceLineDetail(Microsoft.Xrm.Sdk.KeyAttributeCollection keyAttributes) : 
				base(EntityLogicalName, keyAttributes)
		{
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public VSd_InvoiceLineDetail() : 
				base(EntityLogicalName)
		{
		}
		
		public const string PrimaryIdAttribute = "vsd_invoicelinedetailid";
		
		public const string PrimaryNameAttribute = "vsd_name";
		
		public const string EntitySchemaName = "vsd_invoicelinedetail";
		
		public const string EntityLogicalName = "vsd_invoicelinedetail";
		
		public const string EntityLogicalCollectionName = "vsd_invoicelinedetails";
		
		public const string EntitySetName = "vsd_invoicelinedetails";
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyname")]
		public string CreatedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyyominame")]
		public string CreatedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdby"))
				{
					return this.FormattedValues["createdby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("createdonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyname")]
		public string CreatedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfbyyominame")]
		public string CreatedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("createdonbehalfby"))
				{
					return this.FormattedValues["createdonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("importsequencenumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyname")]
		public string ModifiedByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyyominame")]
		public string ModifiedByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedby"))
				{
					return this.FormattedValues["modifiedby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("modifiedonbehalfby", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyname")]
		public string ModifiedOnBehalfByName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfbyyominame")]
		public string ModifiedOnBehalfByYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("modifiedonbehalfby"))
				{
					return this.FormattedValues["modifiedonbehalfby"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("overriddencreatedon", value);
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("ownerid", value);
			}
		}
		
		/// <summary>
		/// Name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridname")]
		public string OwnerIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Yomi name of the owner
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owneridyominame")]
		public string OwnerIdYomiName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("ownerid"))
				{
					return this.FormattedValues["ownerid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("processid", value);
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		[System.Obsolete("This attribute is deprecated.")]
		public System.Nullable<System.Guid> StageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("stageid", value);
			}
		}
		
		/// <summary>
		/// Status of the Invoice Line Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual VSd_InvoiceLineDetail_StateCode? StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((VSd_InvoiceLineDetail_StateCode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecodename")]
		public string StateCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statecode"))
				{
					return this.FormattedValues["statecode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Reason for the status of the Invoice Line Detail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual VSd_InvoiceLineDetail_StatusCode? StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((VSd_InvoiceLineDetail_StatusCode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscodename")]
		public string StatusCodename
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("statuscode"))
				{
					return this.FormattedValues["statuscode"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("timezoneruleversionnumber", value);
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("transactioncurrencyid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyidname")]
		public string TransactionCurrencyIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("transactioncurrencyid"))
				{
					return this.FormattedValues["transactioncurrencyid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		[System.Obsolete("This attribute is deprecated.")]
		public string TraversedPath
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("traversedpath", value);
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UtcConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("utcconversiontimezonecode", value);
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Calculated Amount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_amountcalculated")]
		public Microsoft.Xrm.Sdk.Money VSd_AmountCalculated
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_amountcalculated");
			}
		}
		
		/// <summary>
		/// Value of the Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_amountcalculated_base")]
		public Microsoft.Xrm.Sdk.Money VSd_AmountCalculated_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_amountcalculated_base");
			}
		}
		
		/// <summary>
		/// Input Amount for non-counselling amounts.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_amountsimple")]
		public Microsoft.Xrm.Sdk.Money VSd_AmountSimple
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_amountsimple");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_amountsimple", value);
			}
		}
		
		/// <summary>
		/// Value of the Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_amountsimple_base")]
		public Microsoft.Xrm.Sdk.Money VSd_AmountSimple_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_amountsimple_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_attendingsupportperson")]
		public string VSd_AttendingSupportPerson
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_attendingsupportperson");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_attendingsupportperson", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for Case associated with Invoice Line Detail.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_caseid")]
		public Microsoft.Xrm.Sdk.EntityReference VSd_CaseId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("vsd_caseid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_caseid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_caseidname")]
		public string VsD_CaseiDnaMe
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_caseid"))
				{
					return this.FormattedValues["vsd_caseid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_childcareproviderlastname")]
		public string VSd_ChildCareProviderLastName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_childcareproviderlastname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_childcareproviderlastname", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cpu_programtotal")]
		public Microsoft.Xrm.Sdk.Money VSd_Cpu_ProgramTotal
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_cpu_programtotal");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_cpu_programtotal", value);
			}
		}
		
		/// <summary>
		/// Value of the Program Total in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cpu_programtotal_base")]
		public Microsoft.Xrm.Sdk.Money VSd_Cpu_ProgramTotal_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_cpu_programtotal_base");
			}
		}
		
		/// <summary>
		/// The rate per session for counselling sessions.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cvap_counsellingrate")]
		public Microsoft.Xrm.Sdk.Money VsD_CVaP_CounsellingRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_cvap_counsellingrate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_cvap_counsellingrate", value);
			}
		}
		
		/// <summary>
		/// Value of the Counselling Rate in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cvap_counsellingrate_base")]
		public Microsoft.Xrm.Sdk.Money VsD_CVaP_CounsellingRate_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_cvap_counsellingrate_base");
			}
		}
		
		/// <summary>
		/// The type of counselling session.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cvap_counsellingtype")]
		public virtual VSd_InvoiceLineDetail_VSd_CVAp_CounsellingType? VSd_CVAp_CounsellingType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((VSd_InvoiceLineDetail_VSd_CVAp_CounsellingType?)(EntityOptionSetEnum.GetEnum(this, "vsd_cvap_counsellingtype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_cvap_counsellingtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cvap_counsellingtypename")]
		public string VSd_CVAp_CounsellingTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_cvap_counsellingtype"))
				{
					return this.FormattedValues["vsd_cvap_counsellingtype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cvap_createnewlineitem")]
		public System.Nullable<bool> VSd_CVAp_CreateNewLineItem
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("vsd_cvap_createnewlineitem");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_cvap_createnewlineitem", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cvap_createnewlineitemname")]
		public string VSd_CVAp_CreateNewLineItemName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_cvap_createnewlineitem"))
				{
					return this.FormattedValues["vsd_cvap_createnewlineitem"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Date of counselling session.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cvap_sessiondate")]
		public System.Nullable<System.DateTime> VSd_CVAp_SessionDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("vsd_cvap_sessiondate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_cvap_sessiondate", value);
			}
		}
		
		/// <summary>
		/// The amount in hours of a counselling session.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_cvap_sessionduration")]
		public System.Nullable<decimal> VSd_CVAp_SessionDuration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("vsd_cvap_sessionduration");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_cvap_sessionduration", value);
			}
		}
		
		/// <summary>
		/// Unique identifier for RO Participant Disbursement Transaction associated with Invoice Line Detail.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_disbursementtransactiondetailid")]
		public Microsoft.Xrm.Sdk.EntityReference VSd_DisbursementTransactionDetailId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("vsd_disbursementtransactiondetailid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_disbursementtransactiondetailid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_disbursementtransactiondetailidname")]
		public string VsD_DisbursementTransactionDetailIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_disbursementtransactiondetailid"))
				{
					return this.FormattedValues["vsd_disbursementtransactiondetailid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for Entitlement associated with Invoice Line Item.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_entitlementid")]
		public Microsoft.Xrm.Sdk.EntityReference VSd_EntitlementId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("vsd_entitlementid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_entitlementid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_entitlementidname")]
		public string VSd_EntitlementIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_entitlementid"))
				{
					return this.FormattedValues["vsd_entitlementid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_gst")]
		public Microsoft.Xrm.Sdk.Money VSd_Gst
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_gst");
			}
		}
		
		/// <summary>
		/// Value of the GST in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_gst_base")]
		public Microsoft.Xrm.Sdk.Money VSd_Gst_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_gst_base");
			}
		}
		
		/// <summary>
		/// Unique identifier for Invoice associated with Invoice Line Detail.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_invoiceid")]
		public Microsoft.Xrm.Sdk.EntityReference VSd_InvoiceId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("vsd_invoiceid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_invoiceid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_invoiceidname")]
		public string VSd_InvoiceIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_invoiceid"))
				{
					return this.FormattedValues["vsd_invoiceid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_invoicelinedetailid")]
		public System.Nullable<System.Guid> VSd_InvoiceLineDetailId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("vsd_invoicelinedetailid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_invoicelinedetailid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_invoicelinedetailid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.VSd_InvoiceLineDetailId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_invoicetype")]
		public virtual VSd_InvoiceTypes? VSd_InvoiceType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((VSd_InvoiceTypes?)(EntityOptionSetEnum.GetEnum(this, "vsd_invoicetype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_invoicetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_invoicetypename")]
		public string VSd_InvoiceTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_invoicetype"))
				{
					return this.FormattedValues["vsd_invoicetype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_lineitemapproved")]
		public virtual VSd_YesNo? VSd_LineItemApproved
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((VSd_YesNo?)(EntityOptionSetEnum.GetEnum(this, "vsd_lineitemapproved")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_lineitemapproved", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_lineitemapprovedname")]
		public string VSd_LineItemApprovedName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_lineitemapproved"))
				{
					return this.FormattedValues["vsd_lineitemapproved"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_lineitemdescription")]
		public string VSd_LineItemDescription
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_lineitemdescription");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_lineitemdescription", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_lineitemtotalamount")]
		public Microsoft.Xrm.Sdk.Money VSd_LineItemTotalAmount
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_lineitemtotalamount");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_lineitemtotalamount", value);
			}
		}
		
		/// <summary>
		/// Value of the Line Item Total Amount in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_lineitemtotalamount_base")]
		public Microsoft.Xrm.Sdk.Money VSd_LineItemTotalAmount_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_lineitemtotalamount_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_lineitemtotalsimple")]
		public Microsoft.Xrm.Sdk.Money VSd_LineItemTotalSimple
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_lineitemtotalsimple");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_lineitemtotalsimple", value);
			}
		}
		
		/// <summary>
		/// Value of the lineitemtotalsimple in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_lineitemtotalsimple_base")]
		public Microsoft.Xrm.Sdk.Money VSd_LineItemTotalSimple_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_lineitemtotalsimple_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_missedsession")]
		public System.Nullable<bool> VSd_MissedSession
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("vsd_missedsession");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_missedsession", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_missedsessionname")]
		public string VSd_MissedSessionName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_missedsession"))
				{
					return this.FormattedValues["vsd_missedsession"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// The auto generated Invoice Line Detail number.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_name")]
		public string VSd_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_name", value);
			}
		}
		
		/// <summary>
		/// Set by default on creation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programunit")]
		public virtual VSd_ProgramUnit? VSd_ProgramUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((VSd_ProgramUnit?)(EntityOptionSetEnum.GetEnum(this, "vsd_programunit")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_programunit", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_programunitname")]
		public string VSd_ProgramUnitName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_programunit"))
				{
					return this.FormattedValues["vsd_programunit"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_provincestateid")]
		public Microsoft.Xrm.Sdk.EntityReference VSd_ProvinceStateId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("vsd_provincestateid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_provincestateid", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_provincestateidname")]
		public string VSd_ProvinceStateIdName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_provincestateid"))
				{
					return this.FormattedValues["vsd_provincestateid"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// PST Amount
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_pst")]
		public Microsoft.Xrm.Sdk.Money VSd_Pst
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_pst");
			}
		}
		
		/// <summary>
		/// Value of the PST in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_pst_base")]
		public Microsoft.Xrm.Sdk.Money VSd_Pst_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_pst_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_taxexemption")]
		public virtual VSd_InvoiceLineDetail_VSd_TaxExemption? VSd_TaxExemption
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((VSd_InvoiceLineDetail_VSd_TaxExemption?)(EntityOptionSetEnum.GetEnum(this, "vsd_taxexemption")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_taxexemption", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_taxexemptionname")]
		public string VSd_TaxExemptionName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_taxexemption"))
				{
					return this.FormattedValues["vsd_taxexemption"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_taxrate")]
		public System.Nullable<decimal> VSd_TaxRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("vsd_taxrate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_taxrate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_taxrate2")]
		public System.Nullable<decimal> VSd_TaxRate2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("vsd_taxrate2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_taxrate2", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childage")]
		public System.Nullable<int> VSd_VSu_ChildAge
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("vsd_vsu_childage");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childcareenddate")]
		public System.Nullable<System.DateTime> VSd_VSu_ChildCareEndDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("vsd_vsu_childcareenddate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childcareenddate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childcareprovidercity")]
		public string VSd_VSu_ChildCareProviderCity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_vsu_childcareprovidercity");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childcareprovidercity", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childcareprovidercountry")]
		public string VSd_VSu_ChildCareProviderCountry
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_vsu_childcareprovidercountry");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childcareprovidercountry", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childcareproviderfirstname")]
		public string VSd_VSu_ChildCareProviderFirstName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_vsu_childcareproviderfirstname");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childcareproviderfirstname", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childcareprovidergstbusinessnumber")]
		public string VSd_VSu_ChildCareProviderGstBusinessNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_vsu_childcareprovidergstbusinessnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childcareprovidergstbusinessnumber", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childcareprovidermailaddress1")]
		public string VSd_VSu_ChildCareProviderMailAddress1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_vsu_childcareprovidermailaddress1");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childcareprovidermailaddress1", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childcareprovidermailaddress2")]
		public string VSd_VSu_ChildCareProviderMailAddress2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_vsu_childcareprovidermailaddress2");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childcareprovidermailaddress2", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childcareproviderphoneno")]
		public string VSd_VSu_ChildCareProviderPhoneNo
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_vsu_childcareproviderphoneno");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childcareproviderphoneno", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childcareproviderpostalcode")]
		public string VSd_VSu_ChildCareProviderPostalCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_vsu_childcareproviderpostalcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childcareproviderpostalcode", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childcareproviderprovince")]
		public string VSd_VSu_ChildCareProviderProvince
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_vsu_childcareproviderprovince");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childcareproviderprovince", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_childcarestartdate")]
		public System.Nullable<System.DateTime> VSd_VSu_ChildCaRestartDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("vsd_vsu_childcarestartdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_childcarestartdate", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_dailyroomrate")]
		public Microsoft.Xrm.Sdk.Money VSd_VSu_DailyRoomRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_vsu_dailyroomrate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_dailyroomrate", value);
			}
		}
		
		/// <summary>
		/// Value of the Daily Room Rate in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_dailyroomrate_base")]
		public Microsoft.Xrm.Sdk.Money VSd_VSu_DailyRoomRate_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("vsd_vsu_dailyroomrate_base");
			}
		}
		
		/// <summary>
		/// Line item expense type for VSU invoices.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_expensetype")]
		public virtual VSd_InvoiceLineDetail_VSd_VSu_ExpenseType? VSd_VSu_ExpenseType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((VSd_InvoiceLineDetail_VSd_VSu_ExpenseType?)(EntityOptionSetEnum.GetEnum(this, "vsd_vsu_expensetype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_expensetype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_expensetypename")]
		public string VSd_VSu_ExpenseTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_vsu_expensetype"))
				{
					return this.FormattedValues["vsd_vsu_expensetype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_mileage")]
		public System.Nullable<decimal> VSd_VSu_Mileage
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("vsd_vsu_mileage");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_mileage", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_number")]
		public System.Nullable<int> VSd_VSu_Number
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("vsd_vsu_number");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_number", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_other")]
		public string VSd_VSu_Other
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("vsd_vsu_other");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_other", value);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_transportationtype")]
		public virtual VSd_VSu_TransportationType? VSd_VSu_TransportationType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return ((VSd_VSu_TransportationType?)(EntityOptionSetEnum.GetEnum(this, "vsd_vsu_transportationtype")));
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetAttributeValue("vsd_vsu_transportationtype", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_vsu_transportationtypename")]
		public string VSd_VSu_TransportationTypeName
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				if (this.FormattedValues.Contains("vsd_vsu_transportationtype"))
				{
					return this.FormattedValues["vsd_vsu_transportationtype"];
				}
				else
				{
					return default(string);
				}
			}
		}
		
		/// <summary>
		/// N:1 business_unit_vsd_invoicelinedetail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_vsd_invoicelinedetail")]
		public DataverseModel.BusinessUnit Business_Unit_VSd_InvoiceLineDetail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.BusinessUnit>("business_unit_vsd_invoicelinedetail", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_vsd_invoicelinedetail_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_vsd_invoicelinedetail_createdby")]
		public DataverseModel.SystemUser Lk_VSd_InvoiceLineDetail_CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_vsd_invoicelinedetail_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_vsd_invoicelinedetail_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_vsd_invoicelinedetail_createdonbehalfby")]
		public DataverseModel.SystemUser Lk_VSd_InvoiceLineDetail_CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_vsd_invoicelinedetail_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.SystemUser>("lk_vsd_invoicelinedetail_createdonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 lk_vsd_invoicelinedetail_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_vsd_invoicelinedetail_modifiedby")]
		public DataverseModel.SystemUser Lk_VSd_InvoiceLineDetail_ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_vsd_invoicelinedetail_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_vsd_invoicelinedetail_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_vsd_invoicelinedetail_modifiedonbehalfby")]
		public DataverseModel.SystemUser Lk_VSd_InvoiceLineDetail_ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("lk_vsd_invoicelinedetail_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.SystemUser>("lk_vsd_invoicelinedetail_modifiedonbehalfby", null, value);
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_vsd_invoicelinedetail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_vsd_invoicelinedetail")]
		public DataverseModel.TransactionCurrency TransactionCurrency_VSd_InvoiceLineDetail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.TransactionCurrency>("TransactionCurrency_vsd_invoicelinedetail", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.TransactionCurrency>("TransactionCurrency_vsd_invoicelinedetail", null, value);
			}
		}
		
		/// <summary>
		/// N:1 user_vsd_invoicelinedetail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_vsd_invoicelinedetail")]
		public DataverseModel.SystemUser User_VSd_InvoiceLineDetail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.SystemUser>("user_vsd_invoicelinedetail", null);
			}
		}
		
		/// <summary>
		/// N:1 vsd_vsd_invoice_vsd_invoicelinedetail
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_invoiceid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("vsd_vsd_invoice_vsd_invoicelinedetail")]
		public DataverseModel.VSd_Invoice VSd_VSd_Invoice_VSd_InvoiceLineDetail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.VSd_Invoice>("vsd_vsd_invoice_vsd_invoicelinedetail", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.VSd_Invoice>("vsd_vsd_invoice_vsd_invoicelinedetail", null, value);
			}
		}
		
		/// <summary>
		/// N:1 vsd_vsd_province_vsd_invoicelinedetail_ProvinceStateId
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("vsd_provincestateid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("vsd_vsd_province_vsd_invoicelinedetail_ProvinceStateId")]
		public DataverseModel.VSd_Province VSd_VSd_Province_VSd_InvoiceLineDetail_ProvinceStateId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<DataverseModel.VSd_Province>("vsd_vsd_province_vsd_invoicelinedetail_ProvinceStateId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SetRelatedEntity<DataverseModel.VSd_Province>("vsd_vsd_province_vsd_invoicelinedetail_ProvinceStateId", null, value);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public VSd_InvoiceLineDetail(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (value != null && name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["vsd_invoicelinedetailid"] = base.Id;
                        break;
                    case "vsd_invoicelinedetailid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}
#pragma warning restore CS1591
